### ISSUE TITLE
R-bench-25 not runing fine with rbench.py

### ISSUE THREAD

**Issue by VictorRodriguez** [rbenchmark/benchmarks#4]
$ ../utility/rbench.py R-benchmark-25.R 
Logging the times in rbench.csv
[rbench]R-benchmark-25.R  - Pure warmup run() 2 times
['Rscript', '--vanilla', '/home/vrodri3/BAT/R/benchmarks/utility/r_harness.R', 'TRUE', 'FALSE', '2', 'R-benchmark-25.R', '']
[rbench]R-benchmark-25.R  - Warmup + Bench run() 7 times
['Rscript', '--vanilla', '/home/vrodri3/BAT/R/benchmarks/utility/r_harness.R', 'TRUE', 'FALSE', '7', 'R-benchmark-25.R', '']
[rbench]R-benchmark-25.R  - Metrics for one execution of run()
nan,time
===================  R Benchmark Report ===================
                      2015-07-03 11:10:06 +0000 (CDT)

> > Platform
> > Processor: x86_64 Intel(R) Core(TM) i5-3437U CPU @ 1.90GHz
> > OS: Linux-3.19.3-100.fc20.x86_64-x86_64-with-fedora-20-Heisenbug
> > R Platform: Rscript
> > Benchmarks: 1 Measured
> > time,timestamp,benchmark,args,path,runs,Rscript,RscriptHome,RscriptArgs,env,platform
> > nan,2015-07-03 11:10:06 +0000 (CDT),R-benchmark-25.R,,/home/vrodri3/BAT/R/benchmarks/R-benchmark-25,7,R-bytecode,,--vanilla,R_COMPILE_PKGS=1 R_ENABLE_JIT=2,Linux 3.19.3-100.fc20.x86_64 #1 SMP Fri Mar 27 16:53:47 UTC 2015 x86_64 x86_64

This is taking few seconds,however if I run as ( take the proper time )  : 

$ Rscript R-benchmark-25.R 
Loading required package: Matrix
Loading required package: methods

   R Benchmark 2.5
   ===============
Number of times each test is run__________________________:  3

   I. Matrix calculation

---

Creation, transp., deformation of a 2500x2500 matrix (sec):  1.06433333333333 
2400x2400 normal distributed random matrix ^1000____ (sec):  0.708000000000001 
Sorting of 7,000,000 random values__________________ (sec):  0.867333333333333 
2800x2800 cross-product matrix (b = a' \* a)_________ (sec):  14.706 
Linear regr. over a 3000x3000 matrix (c = a \ b')___ (sec):  6.38866666666667 
                      --------------------------------------------
                 Trimmed geom. mean (2 extremes eliminated):  1.80672190537478 

   II. Matrix functions

---

FFT over 2,400,000 random values____________________ (sec):  0.652333333333336 
Eigenvalues of a 640x640 random matrix______________ (sec):  0.964333333333338 
Determinant of a 2500x2500 random matrix____________ (sec):  2.17666666666666 
hahahCholesky decomposition of a 3000x3000 matrix________ (sec):  1.89099999999999 
Inverse of a 1600x1600 random matrix________________ (sec):  2.24466666666667 
                      --------------------------------------------
                Trimmed geom. mean (2 extremes eliminated):  1.58332551880415 

   III. Programmation

---

3,500,000 Fibonacci numbers calculation (vector calc)(sec):  0.73733333333333 
Creation of a 3000x3000 Hilbert matrix (matrix calc) (sec):  0.278666666666661 
Grand common divisors of 400,000 pairs (recursion)__ (sec):  0.538000000000001 
Creation of a 500x500 Toeplitz matrix (loops)_______ (sec):  0.383333333333345 
Escoufier's method on a 45x45 matrix (mixed)________ (sec):  0.508999999999986 
                      --------------------------------------------
                Trimmed geom. mean (2 extremes eliminated):  0.471728607669131 

Total time for all 15 tests_________________________ (sec):  34.1096666666667 
Overall mean (sum of I, II and III trimmed means/3)_ (sec):  1.10505674235847 
                      --- End of test ---

Why is this ? Am I running something wrong ?

**Comment by wanghc78** [comment]
It seems that the benchmark running with the driver has something wrong. Could you please run it with "--bench_log stdout" like “../utility/rbench.py --bench_log stdout R-benchmark-25.R ”. Then it will dump the commands and logs into your console. And you can check what happened.
